### ISSUE TITLE
[Bug] java.lang.ClassNotFoundException: androidx.appcompat.widget.FitWindowsFrameLayout

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1198]
### Description

I run into the exception in the subject line on the current XE 'develop' branch (tag 1.5.2), when running Samples.Android (in Release mode) on an Android 10 device.

A bisection shows that this issue started with commit 48763efc89ec1753220ef2096e4d065eb7275413 by @jamesmontemagno.

### Steps to Reproduce

1. Open the Xamarin.Essentials solution in VS for Mac.
2. Select 'Samples.Android' and 'Release'.
3. Run.

### Expected Behavior

No exception.

### Actual Behavior

```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Android.Views.InflateException: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Error inflating class androidx.appcompat.widget.FitWindowsFrameLayout ---> Android.Views.InflateException: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Error inflating class androidx.appcompat.widget.FitWindowsFrameLayout ---> Java.Lang.ClassNotFoundException: androidx.appcompat.widget.FitWindowsFrameLayout ---> Java.Lang.ClassNotFoundException: androidx.appcompat.widget.FitWindowsFrameLayout
[MonoDroid]    --- End of inner exception stack trace ---
[chatty] uid=10605(com.xamarin.essentials) identical 1 line
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <b3b2a758492144179f1a4adea5532403>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <b3b2a758492144179f1a4adea5532403>:0 
[MonoDroid]   at AndroidX.AppCompat.App.AppCompatActivity.SetSupportActionBar (AndroidX.AppCompat.Widget.Toolbar toolbar) [0x00031] in <1fcca6d58bc7452697bf870f684c9e40>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState, Xamarin.Forms.Platform.Android.ActivationFlags flags) [0x00129] in <eb32c79d994840809d000f3b2ea82cb7>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <eb32c79d994840809d000f3b2ea82cb7>:0 
[MonoDroid]   at Samples.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00014] in <bb55d352386b44109e9392ff434d52a1>:0 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <bce58432376d425ebb1f0f7c375307a1>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,intptr)
[MonoDroid]   --- End of managed Android.Views.InflateException stack trace ---
[MonoDroid] android.view.InflateException: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Error inflating class androidx.appcompat.widget.FitWindowsFrameLayout
[MonoDroid] Caused by: android.view.InflateException: Binary XML file line #23 in com.xamarin.essentials:layout/abc_screen_simple_overlay_action_mode: Error inflating class androidx.appcompat.widget.FitWindowsFrameLayout
[MonoDroid] Caused by: java.lang.ClassNotFoundException: androidx.appcompat.widget.FitWindowsFrameLayout
[MonoDroid] 	at java.lang.Class.classForName(Native Method)
[MonoDroid] 	at java.lang.Class.forName(Class.java:454)
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:815)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
[MonoDroid] 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:770)
[MonoDroid] 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
[MonoDroid] 	at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:396)
[MonoDroid] 	at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:383)
[MonoDroid] 	at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:419)
[MonoDroid] 	at androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:150)
[MonoDroid] 	at crc64b5364e0bc1f2d6a9.MainActivity.n_onCreate(Native Method)
[MonoDroid] 	at crc64b5364e0bc1f2d6a9.MainActivity.onCreate(MainActivity.java:40)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7839)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7828)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3251)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
[MonoDroid] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:235)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7441)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
[MonoDroid] Caused by: java.lang.ClassNotFoundException: androidx.appcompat.widget.FitWindowsFrameLayout
```

### Basic Information

- Version with issue: 1.5.2
- Last known good version: 1.5.1
- IDE: VS for Mac 8.5
- Platform Target Frameworks:
  - Android: 10
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
I think that if you do a full clean and re-build then the error would go away. Can you give that a try. I have seen it from time to time in other projects, but less frequently.

**Comment by janusw** [comment]
> I think that if you do a full clean and re-build then the error would go away.

No, sorry, that doesn't seem to help. The error only occurs in Release mode, though, not in Debug.


> I have seen it from time to time in other projects, but less frequently.

I see this error message mentioned here, for example: https://github.com/xamarin/AndroidX/issues/64#issuecomment-593414011

**Comment by moljac** [comment]
@janusw 

Try adding something like:

```
-keep public class androidx.appcompat.widget.FitWindowsFrameLayout
```
to your proguard file.

**Comment by janusw** [comment]
> Try adding something like:
> 
> ```
> -keep public class androidx.appcompat.widget.FitWindowsFrameLayout
> ```
> 
> to your proguard file.

Thanks for the hint! That indeed seems to do the trick. Could you explain why this is necessary?

**Comment by moljac** [comment]
Xamarin.Android is not ony .NET world and it seems that R8 (android new shrinker, optimizer, linker) is overly aggressive.

**Comment by jamesmontemagno** [comment]
:) Yay! Weird it isn't happenin in app center builds, but maybe it is on an older build. 

We have Link All on + R8 so that is why everything is going to town :)

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/10138

**Comment by samirgcofficial** [comment]
Encountered in 2022 Feb21 : 
If you not using d8 and R8 code shrinker instead of proguard then you need to add this to your LinkerOption>IgnoreAssemblies>
com.androidx.appcompat.widget.FitWindowsFrameLayout;
This fixed my issue :)

**Comment by MMieszko** [comment]
@samirgcofficial where did you set this?
