### ISSUE TITLE
[Bug] AuthorizationError using WebAuthenticator to login to Apple

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#1268]
### Description

I am implementing WebAuthenticator in my app.
I have it working for Google and Facebook

For iOS it is failing in UWP and iOS (not yet tested on Android)

**on iOS** I am calling await AppleSignInAuthenticator.AuthenticateAsync();
and it throws an exception

 ```
The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
   
  at Xamarin.Essentials.AppleSignInAuthenticator.PlatformAuthenticateAsync (Xamarin.Essentials.AppleSignInAuthenticator+Options options) [0x000b5] in d:\a\1\s\Xamarin.Essentials\WebAuthenticator\AppleSignInAuthenticator.ios.cs:40 
  at ProviderAuthenticator.RemoteProviderLogonHelper.PresentLogin (ProviderAuthenticator.INotifyLastLoginInfo authenticationPersistor) [0x000e6] in C:\projects.vs\classtars\ProviderAuthenticator\RemoteProviderLogonHelper.cs:55 
```
I have added signin permissions to my Entitlements
```
<key>com.apple.developer.applesignin</key>
	<array>
		<string>Default</string>
	</array>
```

and my Provisioning profile shows the following
**Enabled Capabilities**
Game Center, In-App Purchase, Sign In with Apple

**When running on UWP**
I am calling
` result = await WebAuthenticator.AuthenticateAsync(authUrl, callbackUrl);`

The login dialog is displayed and I can enter my userid and password. 
It seems to be working until it tries to return to the app and then throws the exception

```
{"Attempted to perform an unauthorized operation."} 
   
   at Xamarin.Essentials.WebAuthenticator.<PlatformAuthenticateAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProviderAuthenticator.RemoteProviderLogonHelper.<PresentLogin>d__1.MoveNext() in C:\projects.vs\classtars\ProviderAuthenticator\RemoteProviderLogonHelper.cs:line 57
```
  (I have include a short video in the attached zip file)
On the server, the code never reaches the point where it tries to create a callback string.

The same code is working fine for Google and Facebook sign-ins

Any help would be appreciated.,

### Steps to Reproduce

call  await AppleSignInAuthenticator.AuthenticateAsync(); from a Xamarin Client (assume the setup on apple has been completed and you have a valid Provisioning profile.

### Expected Behavior
Should return an access token
### Actual Behavior
throws an com.apple.AuthenticationServices.AuthorizationError error 1000 Exception

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: Xamarin Essentials 1.5.3.1
  - iOS:  11.3
  - UWP:  18362

### Screenshots

[AppleSigninError.zip](https://github.com/xamarin/Essentials/files/4606539/AppleSigninError.zip)

**Comment by solomonfried** [comment]
Just wondering. I was comparing my controller code to the posted Samples. In the samples, the Controller does not declare a callback method /signin-google or /signin-facebook.

In my code I have created a method for each provider
```
     [Route("/signin-google")]
     public object SigninGoogleCallBack() {}
```
My google RedirectUrl was set to https://classtarsnetcoreservices.azurewebsites.net/signin-google
If I did not specify a callback, the Google sign-in would not work.

For some reason, when I started testing I couldn't get Google to authenticate without have a specific Route defined. Now I removed the Route and it is working fine.

So only Apple signin is failing. 
Am I missing something. I have tried various 

In the startup.cs example for the service side there is no mention of CallbackPath as in
```
 .AddGoogle(g =>
  {
      g.ClientId = Configuration["GoogleClientId"];
      g.ClientSecret = Configuration["GoogleClientSecret"];
      g.SaveTokens = true;
   })
```
should there be a g.CallbackPath = "/myAppID:" ???

In my Appe Service IDs I have specified Return URLs as (trying a few hoping something works)

https://classtarsnetcoreservices.azurewebsites.net/signin-apple
https://www.classtarsnetcoreservices.azurewebsites.net/signin-apple
https://classtarsnetcoreservices.azurewebsites.net/applesignin-callback
https://www.classtarsnetcoreservices.azurewebsites.net/applesignin-callback

Thanks for anyone whoi can offer any suggestions

**Comment by solomonfried** [comment]
After much debugging I was able to trace the server code and found that it is throwing an exception..

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 100
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 82
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 48
Application Insights Telemetry: {"name":"AppExceptions","time":"2020-05-11T15:54:57.5804651Z","iKey":"bb33ada9-ef3b-49c6-9a6d-615b3779f27c","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.role":"classtarsnetcoreservices","ai.cloud.roleInstance":"RD00155D95EAB4","ai.operation.id":"dfb7f244e0c7234da02ed2bf6a6dbe66","ai.operation.parentId":"836e92f76ef71e48","ai.operation.name":"POST /signin-apple","ai.location.ip":"74.101.169.165","ai.internal.sdkVersion":"il:2.14.0-17971","ai.internal.nodeName":"RD00155D95EAB4"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"exceptions":[{"id":12633708,"outerId":0,"typeName":"Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException","message":"The system cannot find the file specified.","hasFullStack":true,"parsedStack":[{"level":0,"method":"System.Security.Cryptography.CngKeyLite.ImportKeyBlob","assembly":"System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":1,"method":"System.Security.Cryptography.CngPkcs8.ImportPkcs8","assembly":"System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":2,"method":"System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey","assembly":"System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":3,"method":"System.Security.Cryptography.ECDsaImplementation+ECDsaCng.ImportPkcs8PrivateKey","assembly":"System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0},{"level":4,"method":"AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm","assembly":"AspNet.Security.OAuth.Apple, Version=3.1.1.0, Culture=neutral, PublicKeyToken=fa9e7b608b196fab","fileName":"/_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs","line":100},{"level":5,"method":"AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator+<GenerateNewSecretAsync>d__8.MoveNext","assembly":"AspNet.Security.OAuth.Apple, Version=3.1.1.0, Culture=neutral, PublicKeyToken=fa9e7b608b196fab","fileName":"/_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs","line":82},{"level":6,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":7,"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":8,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":9,"method":"System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":10,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":11,"method":"AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator+<GenerateAsync>d__7.MoveNext","assembly":"AspNet.Security.OAuth.Apple, Version=3.1.1.0, Culture=neutral, PublicKeyToken=fa9e7b608b196fab","fileName":"/_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs","line":48}]}],"severityLevel":"Error","properties":{"ParentId":"0000000000000000","TraceId":"dfb7f244e0c7234da02ed2bf6a6dbe66","RequestPath":"/signin-apple","{OriginalFormat}":"Failed to generate new client secret for the Apple authentication scheme.","_MS.ProcessedByMetricExtractors":"(Name:'Exceptions', Ver:'1.1')","SpanId":"836e92f76ef71e48","FormattedMessage":"Failed to generate new client secret for the Apple authentication scheme.","AspNetCoreEnvironment":"Production","CategoryName":"AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator","RequestId":"80005488-0000-e800-b63f-84710c7967bb"}}}}
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in AspNet.Security.OAuth.Apple.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
Exception thrown: 'Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException' in System.Private.CoreLib.dll
AspNet.Security.OAuth.Apple.AppleAuthenticationHandler: Information: Error from RemoteAuthentication: The system cannot find the file specified..
Exception thrown: 'System.Exception' in Microsoft.AspNetCore.Authentication.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "16717361818409915526", Request ID "80005488-0000-e800-b63f-84710c7967bb": An unhandled exception was thrown by the application.

System.Exception: An error was encountered while handling the remote login.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 100
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 82
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context) in /_/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs:line 48
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext() in /_/src/AspNet.Security.OAuth.Apple/AppleAuthenticationEvents.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context) in /_/src/AspNet.Security.OAuth.Apple/AppleAuthenticationEvents.cs:line 45
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(OAuthCodeExchangeContext context) in /_/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs:line 130
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters) in /_/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs:line 300
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync() in /_/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs:line 202
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   --- End of inner exception stack trace ---
```

I can only assume that this refers to the AuthKey_[appID].p8 file that is specified in the `.AddAuthentication.AddApple(a =>  a.UsePrivateKey(keyId  => WebHostEnvironment.ContentRootFileProvider.GetFileInfo($"AuthKey_{keyId}.p8"));`

The file is definitely there and I can verify that by calling GetFileInfo in another method in the same Controller and reading the file.

**Comment by solomonfried** [comment]
Solved.
For anyone else who comes across this. If your Controller is running on Azure you need to set
WEBSITE_LOAD_USER_PROFILE = 1 in the application settings.

The error is misleading, because the issue is finding a cert that the system is creating at runtime. For whatever reason, that requires loading the user profile which is not available by default in Azure apps.

From what I have read, you can't change this setting on any of the Free Tier App plans. 

Simple solution to an issue that took my a few days to solve.  
I will reach out to the Documentation team and suggest they include this information in the documentation.

**Comment by stesvis** [comment]
> Solved.
> For anyone else who comes across this. If your Controller is running on Azure you need to set
> WEBSITE_LOAD_USER_PROFILE = 1 in the application settings.
> 
> The error is misleading, because the issue is finding a cert that the system is creating at runtime. For whatever reason, that requires loading the user profile which is not available by default in Azure apps.
> 
> From what I have read, you can't change this setting on any of the Free Tier App plans.
> 
> Simple solution to an issue that took my a few days to solve.
> I will reach out to the Documentation team and suggest they include this information in the documentation.

@solomonfried I am having the same error now. Actually, i've never had it but Apple rejected my binary because they encountered this problem.
My backend is .NET Core 5 running on AWS........do you have any idea on how to solve it?
