### ISSUE TITLE
[Bug/Question] [Android] Launcher doesn't work on Huawei Honor 9 with Android 9

### ISSUE THREAD

**Issue by avorobjovs** [xamarin/Essentials#1280]
### Description

Try to open an address "ul. Handlowa 1, 41-807, Zabrze, Poland" in the Google Maps app.

```
var address = "ul. Handlowa 1, 41-807, Zabrze, Poland";
var uri = new Uri(string.Format("geo:0,0?q={0}", WebUtility.UrlEncode(address)));
// uri is "geo:0,0?q=ul.+Handlowa+1%2C+41-807%2C+Zabrze%2C+Poland"

if (await Launcher.CanOpenAsync(uri).ConfigureAwait(true))
{
    await Launcher.OpenAsync(uri).ConfigureAwait(true);
}
```

The Google Maps application is installed on the device and works fine.

### Expected Behavior

The Google Maps application is launched with the specified address.

### Actual Behavior

The Launcher cannot open the provided uri.

The Launcher.CanOpenAsync(uri) method returns FALSE.

The Launcher.OpenAsync(uri) method throws an exception

> Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=geo:xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx flg=0x14001000 }

### Basic Information

Device: Huawei Honor 9 (Model STF-L09)
Android version 9.0

The mobile app is the Xamarin.Forms app.
Xamarin.Forms version 4.4.0.991864
Xamarin.Essentials version 1.5.3.1

**Comment by avorobjovs** [comment]
**Exception full stack trace:**

Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=geo:xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx flg=0x14001000 }
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <0eacbe6b882e45e2b83276a5c4897a8f>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <0eacbe6b882e45e2b83276a5c4897a8f>:0 
  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <b1e2ad3fd9b3496794b549c0e729c9cc>:0 
  at Xamarin.Essentials.Launcher.PlatformOpenAsync (System.Uri uri) [0x00038] in <499a13c41c684d4ca05d73f0c5173f3d>:0 
  at Xamarin.Essentials.Launcher.OpenAsync (System.Uri uri) [0x00014] in <499a13c41c684d4ca05d73f0c5173f3d>:0 
  at KC.Mobility.Technician.PageModels.ServiceRequest.ServiceRequestInformationPageModel.NavigateToAddressAsync () [0x000c2] in <c8d13d0f37214020bf6678bb7d70b9ef>:0 
  at KC.Mobility.Technician.PageModels.ServiceRequest.ServiceRequestInformationPageModel.<.ctor>b__45_0 (System.Object _) [0x0006b] in <c8d13d0f37214020bf6678bb7d70b9ef>:0 
  at KC.Mobility.Technician.Helpers.BaseCommand.Execute (System.Object parameter) [0x00086] in <c8d13d0f37214020bf6678bb7d70b9ef>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <7f8f16ff8a994c79bbc9c0f0e342740b>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <b1e2ad3fd9b3496794b549c0e729c9cc>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <b1e2ad3fd9b3496794b549c0e729c9cc>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <b1e2ad3fd9b3496794b549c0e729c9cc>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.40(intptr,intptr)
  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=geo:xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx flg=0x14001000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2114)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1052)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1009)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at crc643f46942d9dd1fff9.InnerGestureListener.n_onSingleTapUp(Native Method)
	at crc643f46942d9dd1fff9.InnerGestureListener.onSingleTapUp(InnerGestureListener.java:79)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:667)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:65)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:65)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at crc643f46942d9dd1fff9.PlatformRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:47)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:565)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1929)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3594)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)
	at android.view.View.dispatchPointerEvent(View.java:12877)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5771)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5535)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7803)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7768)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7726)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8007)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:202)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:386)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by avorobjovs** [comment]
The same behavior when I try to open a web site.

```
var address = "https://www.abc.com/";
var uri = new Uri(address);

if (await Launcher.CanOpenAsync(uri).ConfigureAwait(true))
{
    await Launcher.OpenAsync(uri).ConfigureAwait(true);
}
```

The Launcher.CanOpenAsync(uri) method returns FALSE.
The Launcher.OpenAsync(uri) method throws an exception

**Comment by jamesmontemagno** [comment]
it is super simple code. try to put this in your main activity and call from there.

When we query for anything that can launch it we ask to see if there are packages. 

```
           var intent = new Intent(Intent.ActionView, AndroidUri.Parse(uri.OriginalString));
            var flags = ActivityFlags.ClearTop | ActivityFlags.NewTask;
            intent.SetFlags(flags);
            StartActivity(intent);
```

It could just not be supported on the Honor 9, maybe their implementation is incorrect.

**Comment by avorobjovs** [comment]
Thank you, James! I will try.

**Comment by avorobjovs** [comment]
Sorry for the long silence. But we had to distribute a fix of our application to testers.

We distribute our app to the Development environment via the Visual Studio App Center. And we distribute our app to the Development environment via the Intune Company Portal.

Currently, we have the following facts:

This feature (opening of external apps) works fine on all iOS devices.
This feature works fine on Android but not Huawei devices.

If we distribute our app via the Visual Studio App Center, this feature also works fine on Huawei devices.
If we distribute our app via the Intune Company Portal, this feature doesn't work on Huawei devices.

It is not related to the code. Both options, the Launcher API and the native Android call StartActivity(intent) have the same results in all cases.

**Comment by jamesmontemagno** [comment]
Thanks for the info. I may then ask the Intune team. Perhaps they block calls externally from apps? Or perhaps the Huawei devices have some incompatibility there. Since the same code doesn't work it isn't anything we can do about it as it isn't on the essential code base.

**Comment by avorobjovs** [comment]
Thank you, James!
If you ask the Intune team, it will be very good. Thank you in advance!

**Comment by avorobjovs** [comment]
Additional investigation is not required anymore.
As it turned out, we also distribute our app via Android Enterprise for some users. And is was the issue related to the Android Work Profile configuration.
