### ISSUE TITLE
[Bug] Android.OS.FileUriExposedException: file:///data/user/0/{AppBundleName}/cache/file.doc exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Essentials#1322]
### Description

> file:// scheme is now not allowed to be attached with Intent on targetSdkVersion 24 (Android Nougat). And here is the solution.

[solution link](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en)

[Original Feature Request](https://github.com/xamarin/Essentials/issues/601)

### Steps to Reproduce

1. download file to the local app cache folder. 
2. create Uri ("file://{path}")
3. boom

### Expected Behavior
open the file when `await Xamarin.Essentials.Launcher.OpenAsync(url).ConfigureAwait(true)` is called.

### Actual Behavior

	Android.OS.FileUriExposedException: file:///data/user/0/{AppBundleName}/cache/file.doc exposed beyond app through Intent.getData()
	  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <eaa205f580954a64824b74a79fa87c62>:0 
	  at Xamarin.Essentials.Launcher.PlatformOpenAsync (System.Uri uri) [0x00033] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.android.cs:35 
	  at Xamarin.Essentials.Launcher.OpenAsync (System.Uri uri) [0x00014] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.shared.cs:38 
	  at {private}.OfficePage.OnAppearing () [0x00071] in D:\{private}.OfficePage.cs:49 
	  --- End of managed Android.OS.FileUriExposedException stack trace ---
	android.os.FileUriExposedException: file:///data/user/0/{AppBundleName}/cache/file.doc exposed beyond app through Intent.getData()
		at android.os.StrictMode.onFileUriExposed(StrictMode.java:2083)
		at android.net.Uri.checkFileUriExposed(Uri.java:2388)
		at android.content.Intent.prepareToLeaveProcess(Intent.java:11478)
		at android.content.Intent.prepareToLeaveProcess(Intent.java:11428)
		at android.app.Instrumentation.execStartActivity(Instrumentation.java:1711)
		at android.app.ContextImpl.startActivity(ContextImpl.java:1000)
		at android.app.ContextImpl.startActivity(ContextImpl.java:971)
		at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
		at crc643f46942d9dd1fff9.PageRenderer.n_onAttachedToWindow(Native Method)
		at crc643f46942d9dd1fff9.PageRenderer.onAttachedToWindow(PageRenderer.java:56)
		at android.view.View.dispatchAttachedToWindow(View.java:21307)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2546)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
		at android.view.Choreographer.doCallbacks(Choreographer.java:797)
		at android.view.Choreographer.doFrame(Choreographer.java:732)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
		at android.os.Handler.handleCallback(Handler.java:883)
		at android.os.Handler.dispatchMessage(Handler.java:100)
		at android.os.Looper.loop(Looper.java:237)
		at android.app.ActivityThread.main(ActivityThread.java:8034)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: unknown
- IDE: Visual Studio 2019 v16.6.3
- Platform Target Frameworks: 
  - iOS:  untested 
  - Android: 10.0  
  - UWP: untested  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
This is weird because we are using the file provider...

https://github.com/xamarin/Essentials/blob/34cc39b736abfd31e993d0d53f62886c06b5af9d/Xamarin.Essentials/Platform/Platform.android.cs#L128

Thanks for the repro, I'll have a look.

**Comment by jamesmontemagno** [comment]
I don't think you want to use "file://" at all. I need to look at the repro, but I think just grab the file name via System.IO and we copy it into temp storage for sharing.... I think. Need to look.

**Comment by Jakar510** [comment]
With **content://{path}** : 

	Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content:///data/user/0/{AppBundleName}/cache/file.doc flg=0x14001000 }
	  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <eaa205f580954a64824b74a79fa87c62>:0 
	  at Xamarin.Essentials.Launcher.PlatformOpenAsync (System.Uri uri) [0x00033] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.android.cs:35 
	  at Xamarin.Essentials.Launcher.OpenAsync (System.Uri uri) [0x00014] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.shared.cs:38 
	  at {Private}.OfficePage.OnAppearing () [0x0007c] in D:\{Private}\OfficePage.cs:62 
	  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
	android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content:///data/user/0/AppBundleName}/cache/file.doc flg=0x14001000 }
		at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2071)
		at android.app.Instrumentation.execStartActivity(Instrumentation.java:1717)
		at android.app.ContextImpl.startActivity(ContextImpl.java:1000)
		at android.app.ContextImpl.startActivity(ContextImpl.java:971)
		at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
		at crc643f46942d9dd1fff9.PageRenderer.n_onAttachedToWindow(Native Method)
		at crc643f46942d9dd1fff9.PageRenderer.onAttachedToWindow(PageRenderer.java:56)
		at android.view.View.dispatchAttachedToWindow(View.java:21307)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2546)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
		at android.view.Choreographer.doCallbacks(Choreographer.java:797)
		at android.view.Choreographer.doFrame(Choreographer.java:732)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
		at android.os.Handler.handleCallback(Handler.java:883)
		at android.os.Handler.dispatchMessage(Handler.java:100)
		at android.os.Looper.loop(Looper.java:237)
		at android.app.ActivityThread.main(ActivityThread.java:8034)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

With **{path}** : 

	Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/data/user/0/AppBundleName}/cache/file.doc flg=0x14001000 }
	  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <9324da45a6654f83baffa7c2854d836a>:0 
	  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <eaa205f580954a64824b74a79fa87c62>:0 
	  at Xamarin.Essentials.Launcher.PlatformOpenAsync (System.Uri uri) [0x00033] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.android.cs:35 
	  at Xamarin.Essentials.Launcher.OpenAsync (System.Uri uri) [0x00014] in d:\a\1\s\Xamarin.Essentials\Launcher\Launcher.shared.cs:38 
	  at {Private}.OfficePage.OnAppearing () [0x0007c] in D:\{Private}\OfficePage.cs:62 
	  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
	android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/data/user/0/AppBundleName}/cache/file.doc flg=0x14001000 }
		at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2071)
		at android.app.Instrumentation.execStartActivity(Instrumentation.java:1717)
		at android.app.ContextImpl.startActivity(ContextImpl.java:1000)
		at android.app.ContextImpl.startActivity(ContextImpl.java:971)
		at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
		at crc643f46942d9dd1fff9.PageRenderer.n_onAttachedToWindow(Native Method)
		at crc643f46942d9dd1fff9.PageRenderer.onAttachedToWindow(PageRenderer.java:56)
		at android.view.View.dispatchAttachedToWindow(View.java:21307)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
		at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2546)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
		at android.view.Choreographer.doCallbacks(Choreographer.java:797)
		at android.view.Choreographer.doFrame(Choreographer.java:732)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
		at android.os.Handler.handleCallback(Handler.java:883)
		at android.os.Handler.dispatchMessage(Handler.java:100)
		at android.os.Looper.loop(Looper.java:237)
		at android.app.ActivityThread.main(ActivityThread.java:8034)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by Jakar510** [comment]
using https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes lets me open the app but can't access the file. 
![e9063abe-166a-427a-a69b-fc2b268973e1](https://user-images.githubusercontent.com/49802225/86966389-b6ef1680-c12e-11ea-8972-3537879a5504.jpg)

**Comment by Jakar510** [comment]
Found a few resources that may help: 

> https://stackoverflow.com/questions/59103133/how-to-directly-download-a-file-to-download-directory-on-android-q-android-10

> https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory

> https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by Jakar510** [comment]
Think I Finally found it.

In Android's implementation of Xamarin.Essentials.Launcher: 


        static Task PlatformOpenAsync(Uri uri)
        {
            var intent = new Intent(Intent.ActionView, AndroidUri.Parse(uri.OriginalString));
            var flags = ActivityFlags.ClearTop | ActivityFlags.NewTask; // **ADD Intent.FLAG_GRANT_READ_URI_PERMISSION**

            #if __ANDROID_24__
            if (Platform.HasApiLevelN)
                flags |= ActivityFlags.LaunchAdjacent;
            #endif

            intent.SetFlags(flags);

            Platform.AppContext.StartActivity(intent);
            return Task.CompletedTask;
        }

**Comment by Jakar510** [comment]
Found a fix: 

For android

	public Task<System.IO.FileInfo> DownloadFile( Uri link, string fileName )
	{
		if ( link is null )
			throw new ArgumentNullException(nameof(link));

		using System.Net.WebClient client = new System.Net.WebClient();

		// MainActivity is the class that loads the application.
		// MainActivity.Instance is a property that you set "Instance = this;" inside of OnCreate.
		Java.IO.File root = MainActivity.Instance.GetExternalFilesDir(MediaStore.Downloads.ContentType);
		string path     = Path.Combine(root.AbsolutePath, fileName);

		client.DownloadFile(link, path);

		return Task.FromResult(new System.IO.FileInfo(path));
	}	
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		internal static MainActivity Instance { get; private set; }
		
		protected override void OnCreate(Bundle savedInstanceState)
		{
			...
			Instance = this;
			...
		}
		...
	}
	
	
	
For iOS

	public Task<System.IO.FileInfo> DownloadFile( Uri link, string fileName )
	{
		if ( link is null )
			throw new ArgumentNullException(nameof(link));

		using System.Net.WebClient client = new System.Net.WebClient();
		string path = Path.Combine(Xamarin.Essentials.FileSystem.CacheDirectory, fileName)
		client.DownloadFile(link, path);

		return Task.FromResult(new System.IO.FileInfo(path));
	}	
	public async Task Share()
	{
		// back in shared project, choose a file name and pass the link.
		System.IO.FileInfo info = await DependencyService.Get<IDownload>().DownloadFile(new Uri("<enter site>", "file.doc").ConfigureAwait(true);
		
		ShareFile shareFile = new ShareFile(info.FullName, "doc"); // enter the file type / extension.
		var request = new ShareFileRequest("Choose the App to open the file", shareFile);
		await Xamarin.Essentials.Share.RequestAsync(request).ConfigureAwait(true);
	}
