### ISSUE TITLE
Linker (and later on runtime) error after the 1.6.1 -> 1.7.0 upgrade

### ISSUE THREAD

**Issue by JanZeman** [xamarin/Essentials#1860]
Hello, not sure this is necessary a bug but it cost me some 30 minutes to find a workaround which might be saved for the others.

After upgrading Xamarin.Essentials from 1.6.1 to 1.7.0 I got the linker error below. I had to manually add two other NuGet packages to get a solution that builds and runs again.

Xamarin.AndroidX.Preference, 1.1.1.8
Xamarin.AndroidX.Arch.Core.Runtime, 2.1.0.8

I haven't tried to get very familiar with this repo code so not sure what is the root cause is. Very probably the NuGet dependency transition.

The error happened obviously on Android, my target SDK is Android 11.

For 1.6.1 version my project explicit NuGet dependency was on Xamarin.Essentials only. For 1.7.0 I had to (hopefully temporarily) add the 2 above dependencies.

`Error		Mono.Linker.MarkException: Error processing method: 'System.Void AndroidX.Preference.Preference::n_OnInitializeAccessibilityNodeInfo_Landroidx_core_view_accessibility_AccessibilityNodeInfoCompat_(System.IntPtr,System.IntPtr,System.IntPtr)' in assembly: 'Xamarin.AndroidX.Preference.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Core.View.Accessibiity.AccessibilityNodeInfoCompat
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	Droid`

**Comment by wcoder** [comment]
Check this #1850

**Comment by JanZeman** [comment]
Yes, must be related to Accessibiity typo fix. I did not notice the double ii in the log.

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/1850#issuecomment-881001888

It could be that there is another dependency that is referencing an older version of a package.

**Comment by holecekp** [comment]
I had the same problem. Xamarin.Essentials 1.7.0 are not compatible with Xamarin.Forms 5.0.0.2012. Debug version works well but the release version cannot be built because of the linker problem.

I need to use Xamarin.Forms 5.0.0.12 because the new version 5.0.0.2083 introduced a regression bug. So I fixed the linker problem by downgrading Xamarin.Essentials from 1.7.0 back to 1.6.1.

The other possible way is to keep Xamarin.Essentials 1.7.0 but upgrade Xamarin.Forms to the latest 5.0.0.2083.
