### ISSUE TITLE
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions

### ISSUE THREAD

**Issue by niels9001** [xamarin/Essentials#289]
On Android, I'm trying to call:

`   GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Low);
     var location = await Geolocation.GetLocationAsync(request);`

At GetLocationAsync I get the following error:

> Error while resolving expression: Object reference not set to an instance of an object

> {Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <7802aa64ad574c33adca332a3fa9706a>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <7802aa64ad574c33adca332a3fa9706a>:0 
  at Android.Support.V4.App.ActivityCompat.RequestPermissions (Android.App.Activity activity, System.String[] permissions, System.Int32 requestCode) [0x00061] in <48bd37de3fc24aa3a0df3b93903114c1>:0 
  at Xamarin.Essentials.Permissions+<PlatformRequestAsync>d__9.MoveNext () [0x001a6] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Xamarin.Essentials.Permissions+<RequireAsync>d__3.MoveNext () [0x00060] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Xamarin.Essentials.Geolocation+<PlatformLocationAsync>d__6.MoveNext () [0x0007b] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at TestApp.Mobile.Views.MainPage+<GetLocation>d__5.MoveNext () [0x00041] in ***Page.cs:73 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:479)
	at md5440e03ce5b057b6078b9acd731a190f3.MainActivity.n_onCreate(Native Method)
	at md5440e03ce5b057b6078b9acd731a190f3.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:7026)
	at android.app.Activity.performCreate(Activity.java:7017)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
}

Looks like this happened after I have updated all the Xamarin.Android NuGet packages to the latest versions?

Running the latest Xamarin.Essentials NuGet package and on the latest Visual Studio 2017 update.

**Comment by jamesmontemagno** [comment]
Is this happening in a Xamarin.Forms application?

**Comment by jamesmontemagno** [comment]
@redth i wonder if we are too aggressive here: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Platform/Platform.android.cs#L106

For mine i had some issues and changed it to never set to null: https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/src/Plugin.CurrentActivity.Android/CurrentActivity/CurrentActivityImplementation.cs#L74

**Comment by jamesmontemagno** [comment]
Do you have a very small reproduction sample that you could share at all?

**Comment by StianCronje** [comment]
I am getting this same error in Xamarin Forms.  I am requesting Geolocation.GetLastKnownLocationAsync on App start. The error does not happen when I use CrossGeolocator to get the location.

**Comment by jamesmontemagno** [comment]
@StianCronje do you have a sample project that you can share? I am not seeing this at all on my end.

**Comment by niels9001** [comment]
Somehow this error disappeared... I just now realize that maybe my app didn't had the permissions in the Android location settings, could that be the reason? If so, maybe a better error message would be helpful. But ideally we'd have something like this: https://github.com/xamarin/Essentials/issues/313

**Comment by StianCronje** [comment]
@jamesmontemagno Here is an example. On my previous project it just happened on my physical device, but here it happens on the emulator as well.

[](https://github.com/StianCronje/GeolocationErrorDemo)

**Comment by Redth** [comment]
I suspect what's happening here is you're trying to get location, which tries to ask for permission, which currently requires an activity to have reached the _resumed_ part of its lifecycle, and you're doing all this before the activity has been initialized and resumed.

This is arguably not the best place to be asking for a user's location, you really should wait to call anything that could require any user interaction (so in Android's case, permission requests) until you've had at least your first Forms' page OnAppearing method called.

We could discuss do a couple of things internally in Essentials:

1. Set the current activity in our lifecycle listener during the `OnCreate` callback (https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Platform/Platform.android.cs#L131) I'm not 100% sure this completely solves the problem - as I'm not sure if we can request permissions before the `OnResume` or not.  This theory would need testing.
2. We could try and hold/delay calls to these API's that require a current activity context until we have one (think `Platform.TaskCompletionSource<Activity> CurrentActivity` or similar) - this approach feels like a lot of hacky code required and still likely to miss cases where it's needed.

**Comment by niels9001** [comment]
I see.. I think putting this into the documentation would already help. What if, in case there is no permission, we return an exception and in case there is just continuing fetchen the location?

**Comment by Redth** [comment]
We should probably add an exception for when we expect `CurrentActivity` to not be null at the very least, with a description about it.

If you do make a call to fetching the location, when the `CurrentActivity` has been properly set on app launch, you should get a `PermissionException` thrown if there are no permissions, or the user has denied permission (https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Permissions/Permissions.shared.cs#L21).  You can catch this one.

**Comment by StianCronje** [comment]
There is a no permission exception being thrown, but its supposed to ask for permission if there is none. I'll try asking after the activity has launched and see if that works.

**Comment by jamesmontemagno** [comment]
@redth we only set the activity on resume... So if someone uses oncreate the activity will be null. We should align to how I did current activity plugin I think to handle this

**Comment by Redth** [comment]
Yes we had a discussion about whether it was correct to set during oncreate and I recall we intentionally did it in onresume. I'd want to do more research before we change this. For example does a previous activity onpause happen before a new ones oncreate is called?  We need to be sure before we make any changes here.

**Comment by jrahma** [comment]
I am having the same error today

Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
  at java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
  at at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:479)
  at at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onAttachedToWindow(Native Method)
  at at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onAttachedToWindow(NavigationPageRenderer.java:49)
  at at android.view.View.dispatchAttachedToWindow(View.java:15395)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2953)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
  at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1516)
  at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
  at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:683)
  at at android.view.Choreographer.doFrame(Choreographer.java:619)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
  at at android.os.Handler.handleCallback(Handler.java:751)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:154)
  at at android.app.ActivityThread.main(ActivityThread.java:6077)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by jrahma** [comment]
Problem solved. Changing the minimum version to 4.4 fixed it.

**Comment by Redth** [comment]
This is definitely the min SDK version we support at runtime currently.
