### ISSUE TITLE
SecureStorage - IKeystoreService.del(java.lang.String, int)' on a null object reference on Huawei devices

### ISSUE THREAD

**Issue by ouma** [xamarin/Essentials#381]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description
After updating to 0.8.0-preview I am getting the error on pre-launch report for Huawei Mate 9 Android 7.0 .
### Steps to Reproduce

1. Launch app
2. App crashes on launch

### Expected Behavior
No error
### Actual Behavior
Throws the following exception

FATAL EXCEPTION: main

java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del(java.lang.String, int)' on a null object reference
	at android.security.KeyStore.delete(KeyStore.java:186)
	at android.security.Credentials.deletePrivateKeyTypeForAlias(Credentials.java:292)
	at android.security.Credentials.deleteAllTypesForAlias(Credentials.java:251)
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:329)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:580)
	at md52b2b0700d3adec667a9b945a5b8b004a.MainActivity.n_onCreate(Native Method)
	at md52b2b0700d3adec667a9b945a5b8b004a.MainActivity.onCreate(MainActivity.java:34)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

### Basic Information

- Version with issue:0.8.0-preview
- Last known good version:0.7.0.17-preview 
- IDE: Visual studio Enterprise 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:8.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:Huawei Mate 9 Android 7.0

**Comment by Redth** [comment]
What's the code in your app?  Specifically how are you using SecureStorage?

**Comment by ouma** [comment]
On application load , I am checking for an app setting (and saving it if it doesn't exist).
Please note that 
- Same code was working fine in the previous version 0.7.0.17-preview
- Only Huawei Mate 9 Android 7.0 is affected on the Pre-launch report , all other devices are working fine

Code
```
var res = await SecureStorage.GetAsync(KEY);      
if (string.IsNullOrEmpty(res))
    await SecureStorage.SetAsync(KEY, value.ToString());
```

**Comment by Redth** [comment]
Are you doing this _after_ you call `Platform.Init` ?

**Comment by ouma** [comment]
Yes.  I am calling the ` Xamarin.Essentials.Platform.Init(this);`  in the MainApplication class.

**Comment by jamesmontemagno** [comment]
This is interesting because we just use the Application.Context itself. This is calling down into KeyGenerator: GenerateKey.

I think that this may be A Huawei Mate 9 issue and not an Essentials issue as we did not change anything here between .7 and .8

**Comment by jamesmontemagno** [comment]
I just bought a device and will get to this next week.

**Comment by jamesmontemagno** [comment]
@ouma where exactly do you call this? I am not able to reproduce this with a Huawei P8 Lite running android 6.0

**Comment by jamesmontemagno** [comment]
picking up a few more devices to test out.

**Comment by jamesmontemagno** [comment]
Just picked up a : Huawei Mate SE running android 7.0. unable to reproduce here :(

**Comment by ouma** [comment]
@jamesmontemagno , I am calling the code on app start. However the error is no longer there though I did not change the code.  I'll let you know in case I am able to reproduce it again.

**Comment by jamesmontemagno** [comment]
maybe we fixed it...?

Can you show me a sample of what call specifically.. is it in your oncreate? onstart? is it in the xamarin.forms application constructor?

**Comment by jamesmontemagno** [comment]
just got the mate 9 and can confirm it is working for me on all huawei devices.
